export const RESUME_DATA: any = {
  name: 'Somasundar',
  initials: 'S',
  location: 'Chennai, Tamil Nadu, India',
  locationLink: 'https://www.google.com/maps/place/Chennai,+Tamil+Nadu',
  summary: '.NET Full Stack Developer',
  about:
    'Results-driven .NET professional with a proven track record of leading teams to deliver practical, scalable solutions aligned with business goals. Passionate about solving complex problems in dynamic environments and committed to continuous learning and professional growth. Proactively stays current with evolving technologies and thrives on collaboration, innovation, and driving impactful outcomes through technical leadership.',
  avatarUrl:
    'https://media.licdn.com/dms/image/v2/C5603AQE_b7BQMedQLQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1602084976280?e=1754524800&v=beta&t=b7uybkXfseA002w-B7vTcB8UlIrUfTtYtljtt1r9xXs',
  personalWebsiteUrl: 'https://somasundar.me',

  email: 'somasundar.work@outlook.com',
  tel: '+91 8344452066',

  github: 'https://github.com/somasundar-work',
  linkedIn: 'https://linkedin.com/in/somasundar-work',
  certifications: [
    {
      name: 'AWS Certified Developer - Associate',
      issuer: 'Amazon Web Services (AWS)',
      link: 'https://www.credly.com/badges/ae676092-290f-4f3d-9c6e-2dc05f5ef3fe',
      logo: 'https://images.credly.com/size/340x340/images/b9feab85-1a43-4f6c-99a5-631b88d5461b/image.png',
      issued: '15th Nov 2024',
      expires: '15th Nov 2027',
    },
  ],
  experiences: [
    {
      company: 'Capgemini',
      position: [
        {
          title: 'Senior Consultant',
          start: 'Aug 2024',
          end: 'Present',
        },
      ],
      location: 'Hybrid - Chennai, Tamil Nadu, India',
      summary:
        'Leading a team of developers to design and implement scalable web applications using .NET Core, Angular, and AWS services. Focused on delivering high-quality software solutions that meet client requirements.',
      techStack: [
        '.NET',
        'C#',
        'Angular',
        'TypeScript',
        'AWS Lambda',
        'S3',
        'CloudWatch',
        'Glue Jobs',
        'DynamoDB',
        'Terraform',
        'MS SQL Server',
        'MangoDB',
        'Git, GitHub',
        'Octopus Deploy',
        'NUnit, Moq',
        'Entity Framework',
        'Dapper',
      ],
      logo: '',
    },
    {
      company: 'Novac Technology Solutions',
      position: [
        {
          title: 'Project Manager',
          start: 'Apr 2024',
          end: 'Aug 2024',
        },
        {
          title: 'Deputy Project Manager',
          start: 'Apr 2022',
          end: 'Mar 2024',
        },
        {
          title: 'Associate Project Manager',
          start: 'Apr 2021',
          end: 'Mar 2022',
        },
        {
          title: 'Senior Software Engineer',
          start: 'Dec 2020',
          end: 'Mar 2021',
        },
      ],
      location: 'On Site - Chennai, Tamil Nadu, India',
      summary:
        'Led a team of developers to design and implement scalable web applications using .NET Core, React, and Azure services. Focused on delivering high-quality software solutions that meet client requirements.',
      techStack: [
        '.NET',
        'C#',
        'React',
        'TypeScript',
        'Git',
        'GitHub',
        'Jenkins',
        'nginx',
        'NUnit',
        'Entity Framework',
        'Docker',
        'Electron.NET',
        'SignalR',
        'Azure App Services',
        'Azure PostgreSQL',
        'Azure Blob Storage',
      ],
      logo: '',
    },
    {
      company: 'Shreyas Technology Solutions Pvt Ltd',
      position: [
        {
          title: 'Web Developer',
          start: 'Sep 2019',
          end: 'Dec 2020',
        },
      ],
      location: 'On Site - Chennai, Tamil Nadu, India',
      summary:
        'Developed and maintained web applications using .NET MVC, focusing on client requirements and technical solutions.',
      techStack: [
        'C#',
        'jQuery',
        'JavaScript',
        'TFS',
        'Bootstrap',
        'WCF',
        'SQL Server',
        'Visual Studio',
        '.NET MVC',
        '.NET Framework',
      ],
      logo: '',
    },
  ],
  education: [
    {
      school: 'Dr. Sivanthi Aditanar College of Engineering',
      // location: 'Tiruchendur, Tamil Nadu, India',
      degree: "Bachelor's Degree in Computer Science and Engineering",
      start: '2016',
      end: '2019',
    },
    {
      school: 'Sankar Polytechnic College',
      // location: 'Tirunelveli, Tamil Nadu, India',
      degree: 'Diploma in Computer Technology',
      start: '2013',
      end: '2016',
    },
  ],
  skills: [
    '.NET',
    '.NET MVC',
    '.NET Framework',
    'C#',
    'Angular',
    'React',
    'TypeScript',
    'AWS Lambda',
    'AWS S3',
    'AWS CloudWatch',
    'AWS Glue Jobs',
    'AWS DynamoDB',
    'Azure App Services',
    'Azure PostgreSQL',
    'Azure Blob Storage',
    'MS SQL Server',
    'MangoDB',
    'PostgreSQL',
    'Octopus Deploy',
    'Entity Framework',
    'Dapper',
    'Git',
    'GitHub',
    'Jenkins',
    'Terraform',
    'Nginx',
    'WCF',
    'RESTful APIs',
    'Microservices',
    'Unit Testing',
    'Visual Studio',
    'Visual Studio Code',
  ],
  projects: [
    {
      title: 'Minimalist CV',
      techStack: ['TypeScript', 'Angular', 'Tailwind CSS'],
      description:
        'An open source minimalist, print friendly CV template with a focus on readability and clean design.',
      logo: 'https://raw.githubusercontent.com/somasundar-work/cv/refs/heads/main/public/icon-512.png',
      link: {
        href: 'https://somasundar-work.github.io/cv/',
        github: 'https://github.com/somasundar-work/cv',
      },
    },
  ],
};
